builds:
  - binary: autobs
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    main: .

aurs:
  - name: autobs-bin
    homepage: "https://github.com/coolapso/autobs"
    description: "Because the most important part of your day shouldn't be explaining to Jira what you did in Git"
    maintainers:
      - "coolapso <coolapso@coolapso.tech>"

    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/autobs-bin.git"
    skip_upload: auto

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
